version: '3'

services:
  django:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn -c gunicorn_config.py Cargo.wsgi:application"
    expose:
      - "8000"
    volumes:
      - .:/code
    depends_on:
      - db
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./configs/site.conf:/etc/nginx/conf.d/site.conf
      - ./static:/data/static
      - ./media:/data/media
    depends_on:
      - django
  db:
    image: postgres
    environment:
      POSTGRES_DATABASE: cargo_db
      POSTGRES_PASSWORD: 123qwe
    ports:
      - "5432:5432"
