INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'deliveries.apps.DeliveriesConfig',
    'orders.apps.OrdersConfig',
    'user_profile.apps.UserProfileConfig',
    'rest_framework',
    'phonenumber_field',
    'rangefilter',
    'multiselectfield',
    'django_cleanup.apps.CleanupConfig',
]
