# Generated by Django 5.0.3 on 2024-09-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorynumber',
            name='location',
        ),
        migrations.AddField(
            model_name='inventorynumber',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='package_type',
            field=models.CharField(choices=[('Cartoon Box', 'Cartoon Box'), ('Envelope', 'Envelope'), ('Scotch Tape Bag', 'Scotch Tape Bag'), ('Case', 'Case')], default='Cartoon Box', max_length=100, verbose_name='Package type'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='state',
            field=models.CharField(choices=[('Perfect', 'Perfect'), ('Broken package', 'Broken Package'), ('Broken item', 'Broken Item'), ('Lost', 'Lost')], default='Perfect', max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Declined', 'Declined'), ('To Deliver', 'To Deliver'), ('Stored', 'Stored'), ('Undecided', 'Undecided')], default='Undecided', max_length=100, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
