# Generated by Django 5.0.3 on 2024-09-06 07:28

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5'), (6, 'Item title 2.2'), (7, 'Item title 2.3'), (8, 'Item title 2.4'), (9, 'Item title 2.2'), (10, 'Item title 2.3'), (11, 'Item title 2.4'), (12, 'Item title 2.2'), (13, 'Item title 2.3'), (14, 'Item title 2.4')], max_length=3),
        ),
    ]
