# Generated by Django 5.0.3 on 2024-09-06 08:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_category_product_delete_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('places_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Places count')),
                ('arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='Arrival date')),
            ],
            options={
                'verbose_name': 'Incoming',
                'verbose_name_plural': 'Incomings',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'indexes': [models.Index(fields=['id'], name='tag_pkey'), models.Index(fields=['name'], name='tag_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='TagIncoming',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.incoming')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.tag')),
            ],
        ),
        migrations.AddField(
            model_name='incoming',
            name='tags',
            field=models.ManyToManyField(blank=True, through='deliveries.TagIncoming', to='deliveries.tag'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddIndex(
            model_name='tagincoming',
            index=models.Index(fields=['incoming_id', 'tag_id'], name='tag_incoming_idx'),
        ),
        migrations.AddIndex(
            model_name='incoming',
            index=models.Index(fields=['id'], name='incoming_idx'),
        ),
        migrations.AddIndex(
            model_name='incoming',
            index=models.Index(fields=['name'], name='imcoming_name_idx'),
        ),
    ]
