# Generated by Django 5.0.3 on 2024-09-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_incoming_remove_product_categories_tag_tagincoming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='package_type',
            field=models.CharField(choices=[('Cartoon Box', 'Cartoon Box'), ('Envelope', 'Envelope'), ('Scotch Tape Bag', 'Scotch Tape Bag'), ('Case', 'Case')], default='Cartoon Box', max_length=100, verbose_name='Package type'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='photo_path',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo path'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='size',
            field=models.CharField(blank=True, default='0x0x0', verbose_name='Size (LxHxW)'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='state',
            field=models.CharField(choices=[('Perfect', 'Perfect'), ('Broken package', 'Broken Package'), ('Broken item', 'Broken Item'), ('Lost', 'Lost')], default='Perfect', max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='weight',
            field=models.IntegerField(blank=True, default=10, verbose_name='Weight (kg)'),
        ),
    ]
