# Generated by Django 5.0.3 on 2024-09-06 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_remove_incoming_imcoming_name_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='image',
        ),
        migrations.AlterField(
            model_name='incoming',
            name='package_type',
            field=models.CharField(choices=[('Cartoon Box', 'Cartoon Box'), ('Envelope', 'Envelope'), ('Scotch Tape Bag', 'Scotch Tape Bag'), ('Case', 'Case')], default='Cartoon Box', max_length=100, verbose_name='Package type'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='state',
            field=models.CharField(choices=[('Perfect', 'Perfect'), ('Broken package', 'Broken Package'), ('Broken item', 'Broken Item'), ('Lost', 'Lost')], default='Perfect', max_length=100, verbose_name='State'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='images/')),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_set', to='deliveries.incoming')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoIncoming',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.incoming')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.photo')),
            ],
        ),
        migrations.AddField(
            model_name='incoming',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='incoming_images', through='deliveries.PhotoIncoming', to='deliveries.photo'),
        ),
        migrations.AddIndex(
            model_name='photoincoming',
            index=models.Index(fields=['incoming_id', 'photo_id'], name='photo_incoming_idx'),
        ),
    ]
