# Generated by Django 5.0.3 on 2024-09-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0088_alter_incoming_package_type_alter_incoming_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='package_type',
            field=models.CharField(choices=[('Cartoon Box', 'Cartoon Box'), ('Envelope', 'Envelope'), ('Scotch Tape Bag', 'Scotch Tape Bag'), ('Case', 'Case')], default='Cartoon Box', max_length=100, verbose_name='Package type'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='state',
            field=models.CharField(choices=[('Perfect', 'Perfect'), ('Broken package', 'Broken Package'), ('Broken item', 'Broken Item'), ('Lost', 'Lost')], default='Perfect', max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Declined', 'Declined'), ('To Deliver', 'To Deliver'), ('Stored', 'Stored'), ('Undecided', 'Undecided')], default='Undecided', max_length=100, verbose_name='Status'),
        ),
    ]
